### PR TITLE
Consolidate outstanding forks

### PR DESCRIPTION
**Pull request by esben**
Would you consider merging this PR, or alternatively the different branches I merged here in separate PR's?

### CODE REVIEW

**Comment by msabramo** [comment]
Thanks for the work! Sorry for not giving this more attention.

Unfortunately, there's a failing test, if you look at the Travis CI results at https://travis-ci.org/msabramo/requests-unixsocket/builds/79349571

**Comment by msabramo** [comment]
I think I might see why the test is failing. Shouldn't it be this?

```diff
diff --git a/requests_unixsocket/tests/test_requests_unixsocket.py b/requests_unixsocket/tests/test_requests_unixsocket.py
index 304736a..34151b2 100755
--- a/requests_unixsocket/tests/test_requests_unixsocket.py
+++ b/requests_unixsocket/tests/test_requests_unixsocket.py
@@ -85,7 +85,7 @@ def test_unix_domain_adapter_connection_proxies_error():
         with pytest.raises(ValueError) as excinfo:
             getattr(session, method)(
                 'http+unix://socket_does_not_exist/path/to/page',
-                proxies={"http": "http://10.10.1.10:1080"})
+                proxies={"http+unix": "http://10.10.1.10:1080"})
         assert ('UnixAdapter does not support specifying proxies'
                 in str(excinfo.value))
```

Otherwise, it wouldn't try to use that proxy, right?

**Comment by esben** [comment]
Seems like you were right :)

**Comment by msabramo** [comment]
Thanks, @esben!

**Comment by msabramo** [comment]
Thanks again and released this in https://pypi.python.org/pypi/requests-unixsocket/0.1.5

**Comment by esben** [comment]
Thanks!

**Pull request merged**
